### ISSUE TITLE
Error loading Automatic CFG - no module named "colorama"

### ISSUE THREAD

**Issue by ricperry** [Extraltodeus/ComfyUI-AutomaticCFG#14]
Just updated the node, and now I'm getting this error:

```
Traceback (most recent call last):
  File "~/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "~/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG/__init__.py", line 1, in <module>
    from .nodes import *
  File "~/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG/nodes.py", line 7, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'

Cannot import /home/ricperry1/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG module for custom nodes: No module named 'colorama'
```

Not sure what changed. Thought maybe it was a ComfyUI baseline update, but nodes.py most recent change is in this package, not comfy's package, which had been working fine until this morning.

**Comment by Extraltodeus** [comment]
Oh,

    pip install colorama

I added a few colors.
