### ISSUE TITLE
Some conflict. Doesn't load.

### ISSUE THREAD

**Issue by elphamale** [Extraltodeus/ComfyUI-AutomaticCFG#20]
Getting import failed on comfy start.

here's the console output:

`Total VRAM 12288 MB, total RAM 65277 MB
xformers version: 0.0.22
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints E:\StableDiffusion\StabilityMatrix\Models\StableDiffusion
Adding extra search path vae E:\StableDiffusion\StabilityMatrix\Models\VAE
Adding extra search path loras E:\StableDiffusion\StabilityMatrix\Models\Lora
Adding extra search path loras E:\StableDiffusion\StabilityMatrix\Models\LyCORIS
Adding extra search path upscale_models E:\StableDiffusion\StabilityMatrix\Models\ESRGAN
Adding extra search path upscale_models E:\StableDiffusion\StabilityMatrix\Models\RealESRGAN
Adding extra search path upscale_models E:\StableDiffusion\StabilityMatrix\Models\SwinIR
Adding extra search path embeddings E:\StableDiffusion\StabilityMatrix\Models\TextualInversion
Adding extra search path hypernetworks E:\StableDiffusion\StabilityMatrix\Models\Hypernetwork
Adding extra search path controlnet E:\StableDiffusion\StabilityMatrix\Models\ControlNet
Adding extra search path clip E:\StableDiffusion\StabilityMatrix\Models\CLIP
Adding extra search path diffusers E:\StableDiffusion\StabilityMatrix\Models\Diffusers
Adding extra search path gligen E:\StableDiffusion\StabilityMatrix\Models\GLIGEN
Adding extra search path vae_approx E:\StableDiffusion\StabilityMatrix\Models\ApproxVAE
Web extensions folder found at E:\StableDiffusion\ComfyUI\web\extensions\ComfyLiterals
Traceback (most recent call last):
  File "E:\StableDiffusion\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\__init__.py", line 2, in <module>
    from .nodes_sag_custom import *
  File "E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\nodes_sag_custom.py", line 8, in <module>
    from comfy.ldm.modules.attention import optimized_attention, _ATTN_PRECISION
ImportError: cannot import name '_ATTN_PRECISION' from 'comfy.ldm.modules.attention' (E:\StableDiffusion\ComfyUI\comfy\ldm\modules\attention.py)

Cannot import E:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG module for custom nodes: cannot import name '_ATTN_PRECISION' from 'comfy.ldm.modules.attention' (E:\StableDiffusion\ComfyUI\comfy\ldm\modules\attention.py)`

**Comment by Extraltodeus** [comment]
Update the node

**Comment by elphamale** [comment]
Sorry, I forgot to close this issue.

I did update yesterday a hour after my message above and it loaded.
