### ISSUE TITLE
AutoCfg update failing

### ISSUE THREAD

**Issue by ashxtrem** [Extraltodeus/ComfyUI-AutomaticCFG#25]
`Traceback (most recent call last):
  File "Z:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Z:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\__init__.py", line 2, in <module>        
    from .nodes_sag_custom import *
  File "Z:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\nodes_sag_custom.py", line 8, in <module>
    from comfy.ldm.modules.attention import optimized_attention, _ATTN_PRECISION
ImportError: cannot import name '_ATTN_PRECISION' from 'comfy.ldm.modules.attention' (Z:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\comfy\ldm\modules\attention.py)`

Env
`.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen --force-fp16 --disable-auto-launch 
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-20 21:58:15.688240
** Platform: Windows
** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Total VRAM 16380 MB, total RAM 48908 MB
pytorch version: 2.4.0.dev20240408+cu121
Forcing FP16.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
`

**Comment by Extraltodeus** [comment]
You did not update to the latest version because I commented out the import triggering the error.

Update to the latest version.

**Comment by ashxtrem** [comment]
Updating comfyui solved the issue.
