### ISSUE TITLE
(IMPORT FAILED) cannot import name 'set_model_options_patch_replace' from 'comfy.model_patcher'

### ISSUE THREAD

**Issue by TIMETSS** [Extraltodeus/ComfyUI-AutomaticCFG#33]
Traceback (most recent call last):
  File "D:\Program\AI\ComfyUI\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\__init__.py", line 1, in <module>
    from .nodes import *
  File "D:\Program\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\nodes.py", line 5, in <module>
    from comfy.model_patcher import set_model_options_patch_replace
ImportError: cannot import name 'set_model_options_patch_replace' from 'comfy.model_patcher' (D:\Program\AI\ComfyUI\ComfyUI\comfy\model_patcher.py)

Cannot import D:\Program\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG module for custom nodes: cannot import name 'set_model_options_patch_replace' from 'comfy.model_patcher' (D:\Program\AI\ComfyUI\ComfyUI\comfy\model_patcher.py)

**Comment by Extraltodeus** [comment]
Hello, have you updated Comfy?

**Comment by Yao544303** [comment]
Hello, I faced the same issue, do you fix it?

**Comment by Extraltodeus** [comment]
Hello!

The thing is that comfy.model_patcher.set_model_options_patch_replace does exist so why can't it not find it in your setup?

Can you try without rgthree-comfy ?
